name: .NET

on: [push]
#on:
#  push:
#    branches: [ $default-branch ]
#  pull_request:
#    branches: [ $default-branch ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test -c Release --no-build --logger:junit --collect:"XPlat Code Coverage" --results-directory ./test-results --settings coverlet.runsettings

    - name: Publish Test Results
      uses: phoenix-actions/test-reporting@v12
      id: test-report
      if: success() || failure()
      with:
        name: Tests Results
        path: ./test-results/*.xml
        reporter: jest-junit

    - name: Publish Coberage Results
      uses: 5monkeys/cobertura-action@v13
      with:
        path: ./test-results/**/coverage.*.xml
        minimum_coverage: 0
        show_line: true
        show_branch: true
        show_class_names: true
        report_name: Coverage